main: main.Main
version: 1.0.0
name: PUBGMap
softdepend: [WorldBorderAPI]
commands:
 next:
   usage: /<command> [size] [delay] [time]
   permission: op
   permission-message: "§4このコマンドを実行するための権限がありません！"
 givemap:
   usage: /<command> [playerID(任意)]
   permission: op
   permission-message: "§4このコマンドを実行するための権限がありません！"
 resetmap:
   usage: /<command>
   permission: op
   permission-message: "§4このコマンドを実行するための権限がありません！"
 clearmap:
   usage: /<command>
   permission: op
   permission-message: "§4このコマンドを実行するための権限がありません！"
permissions:
  op:
    default: op